FROM python:3.7
RUN pip install opentelemetry-api opentelemetry-auto-instrumentation opentelemetry-ext-lightstep requests
ADD client.py /app/client.py
CMD ["opentelemetry-auto-instrumentation", "/app/client.py"]
