FROM openjdk:8

RUN mkdir /app
RUN wget -P /app/ https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-auto-all.jar

ADD target/lightstep-otlp-server.jar /app/

ENTRYPOINT java \
        -jar /app/lightstep-otlp-server.jar\
        com.lightstep.otlp.server.ExampleServer
